const SUPABASE_URL = "https://gitnhcnhwkjyzebujsxn.supabase.co";
const SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpdG5oY25od2tqeXplYnVqc3huIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzI5NjYyNCwiZXhwIjoyMDkyODcyNjI0fQ.q1DOAc0A_SDb_Lf6fps1D73_1Padc4jshYmZFR7o5Ps";
const USER_ID = "e1fa1e61-3c19-4f1e-85c1-a98b51dd9da7";

const tools = [
  { name: "ChatGPT", slug: "chatgpt", url: "https://chat.openai.com", subcategory_id: 81, subcategory_snapshot: "Chat", pricing: "Freemium", overview: "ChatGPT is an AI-powered conversational assistant by OpenAI that can answer questions, write code, draft content, and more.", key_features: ["Multi-turn conversation", "Code generation", "Image understanding", "Custom GPTs"], use_cases: ["Customer support", "Content writing", "Programming help"], pros: ["Very capable", "Wide knowledge base"], cons: ["Can hallucinate", "Limited free tier"] },
  { name: "Midjourney", slug: "midjourney", url: "https://midjourney.com", subcategory_id: 6, subcategory_snapshot: "Image", pricing: "Paid", overview: "Midjourney is an AI image generation tool that creates stunning visuals from text prompts via Discord.", key_features: ["Text-to-image", "High quality art", "Style customization", "V6 model"], use_cases: ["Graphic design", "Art creation", "Marketing visuals"], pros: ["Exceptional image quality", "Active community"], cons: ["Requires Discord", "No free plan"] },
  { name: "GitHub Copilot", slug: "github-copilot", url: "https://github.com/features/copilot", subcategory_id: 28, subcategory_snapshot: "Code", pricing: "Paid", overview: "GitHub Copilot is an AI pair programmer that suggests code completions and entire functions directly in your editor.", key_features: ["Code autocomplete", "Multi-language support", "IDE integration", "Chat mode"], use_cases: ["Software development", "Code review", "Bug fixing"], pros: ["Fast suggestions", "Supports many languages"], cons: ["Subscription required", "Occasional wrong suggestions"] },
  { name: "Notion AI", slug: "notion-ai", url: "https://notion.so/product/ai", subcategory_id: 14, subcategory_snapshot: "Productivity", pricing: "Freemium", overview: "Notion AI brings AI-powered writing, summarization, and task management directly into your Notion workspace.", key_features: ["AI writing", "Summarization", "Action items extraction", "Translation"], use_cases: ["Note-taking", "Project management", "Team wikis"], pros: ["Seamless Notion integration", "Easy to use"], cons: ["Requires Notion subscription", "Limited standalone use"] },
  { name: "Runway ML", slug: "runway-ml", url: "https://runwayml.com", subcategory_id: 7, subcategory_snapshot: "Video", pricing: "Freemium", overview: "Runway is a creative AI platform for video generation, editing, and visual effects used by filmmakers and creators.", key_features: ["Text-to-video", "Video inpainting", "Green screen", "Motion tracking"], use_cases: ["Film production", "Social media content", "Visual effects"], pros: ["Professional quality", "Many tools in one"], cons: ["Expensive credits", "Processing time"] },
  { name: "Jasper AI", slug: "jasper-ai", url: "https://jasper.ai", subcategory_id: 20, subcategory_snapshot: "Marketing", pricing: "Paid", overview: "Jasper is an AI writing assistant designed for marketing teams to create high-converting copy, blogs, and campaigns.", key_features: ["Brand voice", "Campaign builder", "SEO mode", "Templates"], use_cases: ["Blog writing", "Ad copy", "Email marketing"], pros: ["Marketing focused", "Team collaboration"], cons: ["Expensive", "Learning curve"] },
  { name: "ElevenLabs", slug: "elevenlabs", url: "https://elevenlabs.io", subcategory_id: 10, subcategory_snapshot: "Voice", pricing: "Freemium", overview: "ElevenLabs provides ultra-realistic AI voice synthesis and cloning for creators, developers, and businesses.", key_features: ["Voice cloning", "Text-to-speech", "29 languages", "API access"], use_cases: ["Audiobooks", "Podcasts", "Game characters"], pros: ["Most realistic voices", "Easy cloning"], cons: ["Limited free credits", "Misuse concerns"] },
  { name: "Perplexity AI", slug: "perplexity-ai", url: "https://perplexity.ai", subcategory_id: 35, subcategory_snapshot: "Research", pricing: "Freemium", overview: "Perplexity AI is an AI-powered search engine that provides direct answers with cited sources in real time.", key_features: ["Real-time search", "Source citations", "Follow-up questions", "Copilot mode"], use_cases: ["Research", "Fact checking", "Learning"], pros: ["Cited sources", "Fast and accurate"], cons: ["Pro features cost", "Occasional outdated info"] },
  { name: "Claude", slug: "claude", url: "https://claude.ai", subcategory_id: 81, subcategory_snapshot: "Chat", pricing: "Freemium", overview: "Claude is Anthropic's AI assistant known for being helpful, harmless, and honest with a very large context window.", key_features: ["200K context window", "Document analysis", "Code writing", "Safety focused"], use_cases: ["Document analysis", "Long-form writing", "Research"], pros: ["Huge context window", "Safe outputs"], cons: ["Limited free usage", "No image generation"] },
  { name: "Stable Diffusion", slug: "stable-diffusion", url: "https://stability.ai", subcategory_id: 6, subcategory_snapshot: "Image", pricing: "Free", overview: "Stable Diffusion is an open-source AI image generation model that runs locally or via API for text-to-image creation.", key_features: ["Open source", "Local deployment", "ControlNet", "Inpainting"], use_cases: ["Art creation", "Product mockups", "Research"], pros: ["Free and open source", "Highly customizable"], cons: ["Requires hardware", "Setup complexity"] },
  { name: "Synthesia", slug: "synthesia", url: "https://synthesia.io", subcategory_id: 7, subcategory_snapshot: "Video", pricing: "Paid", overview: "Synthesia creates AI-generated videos with realistic avatars from text scripts, used for training and presentations.", key_features: ["AI avatars", "140+ languages", "Screen recorder", "Templates"], use_cases: ["Corporate training", "Explainer videos", "Marketing"], pros: ["No camera needed", "Multilingual"], cons: ["Expensive plans", "Avatar limitations"] },
  { name: "Copy.ai", slug: "copy-ai", url: "https://copy.ai", subcategory_id: 20, subcategory_snapshot: "Marketing", pricing: "Freemium", overview: "Copy.ai is an AI copywriting tool that helps marketers and businesses generate compelling content quickly.", key_features: ["90+ templates", "Workflow automation", "Brand voice", "Multi-language"], use_cases: ["Ad copy", "Product descriptions", "Social posts"], pros: ["Easy to use", "Many templates"], cons: ["Quality varies", "Limited context"] },
  { name: "Otter.ai", slug: "otter-ai", url: "https://otter.ai", subcategory_id: 17, subcategory_snapshot: "Meetings", pricing: "Freemium", overview: "Otter.ai provides real-time AI transcription and meeting notes for teams, integrating with Zoom, Google Meet, and Teams.", key_features: ["Live transcription", "Meeting summaries", "Speaker identification", "Action items"], use_cases: ["Meeting notes", "Interview transcription", "Lectures"], pros: ["Accurate transcription", "Easy sharing"], cons: ["Limited free minutes", "Accuracy with accents"] },
  { name: "Grammarly", slug: "grammarly", url: "https://grammarly.com", subcategory_id: 14, subcategory_snapshot: "Productivity", pricing: "Freemium", overview: "Grammarly is an AI writing assistant that checks grammar, spelling, style, and tone across all your writing platforms.", key_features: ["Grammar check", "Tone detection", "Plagiarism check", "Browser extension"], use_cases: ["Professional writing", "Academic writing", "Email"], pros: ["Works everywhere", "Detailed suggestions"], cons: ["Premium is expensive", "Can over-correct"] },
  { name: "Lumen5", slug: "lumen5", url: "https://lumen5.com", subcategory_id: 7, subcategory_snapshot: "Video", pricing: "Freemium", overview: "Lumen5 transforms blog posts and text into engaging marketing videos using AI-powered automation.", key_features: ["Blog to video", "Stock library", "Brand kit", "Auto layout"], use_cases: ["Content marketing", "Social media", "News"], pros: ["Very fast workflow", "No video skills needed"], cons: ["Watermark on free", "Limited customization"] },
  { name: "Murf AI", slug: "murf-ai", url: "https://murf.ai", subcategory_id: 9, subcategory_snapshot: "Audio", pricing: "Freemium", overview: "Murf AI is a text-to-speech platform with studio-quality voices for voiceovers, e-learning, and presentations.", key_features: ["120+ voices", "Voice changer", "Sync with video", "Team collaboration"], use_cases: ["E-learning", "Presentations", "Podcasts"], pros: ["Professional quality", "Easy editor"], cons: ["Credits expire", "Limited free plan"] },
  { name: "Writesonic", slug: "writesonic", url: "https://writesonic.com", subcategory_id: 20, subcategory_snapshot: "Marketing", pricing: "Freemium", overview: "Writesonic is an AI writing platform for creating SEO-optimized blogs, ads, landing pages, and chatbots.", key_features: ["SEO optimization", "Chatsonic AI", "Bulk generation", "Zapier integration"], use_cases: ["Blog writing", "Landing pages", "Ad copy"], pros: ["SEO focused", "Real-time data via Chatsonic"], cons: ["Quality inconsistent", "Credit system confusing"] },
  { name: "Descript", slug: "descript", url: "https://descript.com", subcategory_id: 7, subcategory_snapshot: "Video", pricing: "Freemium", overview: "Descript is an all-in-one video and podcast editor that lets you edit media by editing text transcripts.", key_features: ["Overdub voice cloning", "Screen recording", "Text-based editing", "Filler word removal"], use_cases: ["Podcast editing", "YouTube videos", "Training videos"], pros: ["Revolutionary editing approach", "Great for beginners"], cons: ["Large file sizes", "Overdub quality varies"] },
  { name: "Suno AI", slug: "suno-ai", url: "https://suno.ai", subcategory_id: 11, subcategory_snapshot: "Music", pricing: "Freemium", overview: "Suno AI generates full songs with vocals and instruments from simple text prompts in seconds.", key_features: ["Full song generation", "Custom lyrics", "Multiple genres", "API access"], use_cases: ["Music creation", "Content soundtracks", "Demos"], pros: ["Remarkably good quality", "Very fast"], cons: ["Copyright unclear", "Limited control"] },
  { name: "Beautiful.ai", slug: "beautiful-ai", url: "https://beautiful.ai", subcategory_id: 19, subcategory_snapshot: "Presentations", pricing: "Paid", overview: "Beautiful.ai uses AI to automatically design stunning presentations that adapt layout as you add content.", key_features: ["Smart slide templates", "Auto-design", "Brand kit", "Analytics"], use_cases: ["Business presentations", "Pitch decks", "Reports"], pros: ["Designs itself", "Professional output"], cons: ["No offline mode", "Limited free tier"] },
  { name: "Zapier AI", slug: "zapier-ai", url: "https://zapier.com/ai", subcategory_id: 15, subcategory_snapshot: "Automation", pricing: "Freemium", overview: "Zapier AI lets you build automation workflows using natural language, connecting thousands of apps without code.", key_features: ["Natural language automation", "5000+ app integrations", "AI actions", "Chatbots"], use_cases: ["Workflow automation", "Data sync", "Lead management"], pros: ["Huge app library", "No-code"], cons: ["Can be slow", "Complex pricing"] },
  { name: "Pictory", slug: "pictory", url: "https://pictory.ai", subcategory_id: 7, subcategory_snapshot: "Video", pricing: "Paid", overview: "Pictory converts long-form content like scripts and articles into short branded video clips automatically.", key_features: ["Script to video", "Auto highlights", "Caption generation", "Stock footage"], use_cases: ["Social media clips", "Course content", "Marketing"], pros: ["Fast video creation", "Good stock library"], cons: ["Limited customization", "Watermark on basic"], gods: [] },
  { name: "Tome", slug: "tome", url: "https://tome.app", subcategory_id: 19, subcategory_snapshot: "Presentations", pricing: "Freemium", overview: "Tome is an AI-native storytelling format that helps you build compelling narratives and presentations from prompts.", key_features: ["AI narrative builder", "Embed anything", "Live data tiles", "Presenter mode"], use_cases: ["Pitch decks", "Storytelling", "Product demos"], pros: ["Unique format", "Fast creation"], cons: ["Not traditional slides", "Limited exports"] },
  { name: "Notion AI Q&A", slug: "notion-ai-qa", url: "https://notion.so", subcategory_id: 35, subcategory_snapshot: "Research", pricing: "Freemium", overview: "Notion AI Q&A lets you ask questions about your entire workspace and get instant answers from your notes and docs.", key_features: ["Workspace search", "Q&A mode", "Instant answers", "Context aware"], use_cases: ["Knowledge management", "Team wikis", "Research"], pros: ["Uses your own data", "Deeply integrated"], cons: ["Requires large workspace", "Notion subscription"] },
  { name: "HeyGen", slug: "heygen", url: "https://heygen.com", subcategory_id: 7, subcategory_snapshot: "Video", pricing: "Freemium", overview: "HeyGen creates AI-powered video content with talking avatars and voice cloning for personalized video at scale.", key_features: ["Avatar videos", "Voice cloning", "Video translation", "Interactive avatar"], use_cases: ["Sales outreach", "Corporate training", "Marketing"], pros: ["Highly personalized", "Video translation"], cons: ["Expensive at scale", "Rendering time"] },
  { name: "Pika Labs", slug: "pika-labs", url: "https://pika.art", subcategory_id: 7, subcategory_snapshot: "Video", pricing: "Freemium", overview: "Pika is an AI video generation platform that creates and edits videos from text and image prompts.", key_features: ["Text-to-video", "Image-to-video", "Video editing", "Sound effects"], use_cases: ["Short clips", "Social media", "Animation"], pros: ["Easy to use", "Good quality"], cons: ["Short video length", "Limited control"] },
  { name: "Ideogram", slug: "ideogram", url: "https://ideogram.ai", subcategory_id: 6, subcategory_snapshot: "Image", pricing: "Freemium", overview: "Ideogram is an AI image generator that excels at creating images with accurate, readable text embedded in designs.", key_features: ["Text in images", "Style presets", "Magic prompt", "Remix"], use_cases: ["Logo concepts", "Poster design", "Typography art"], pros: ["Best text-in-image AI", "Free tier generous"], cons: ["Slower than competitors", "Limited editing"] },
  { name: "Gamma", slug: "gamma", url: "https://gamma.app", subcategory_id: 19, subcategory_snapshot: "Presentations", pricing: "Freemium", overview: "Gamma is an AI-powered tool that generates beautiful presentations, documents, and webpages from a simple prompt.", key_features: ["One-click generation", "Web-based", "Embed media", "Analytics"], use_cases: ["Presentations", "Reports", "Landing pages"], pros: ["Fastest deck creation", "Modern design"], cons: ["Less control than PowerPoint", "Limited themes"] },
  { name: "Elicit", slug: "elicit", url: "https://elicit.com", subcategory_id: 35, subcategory_snapshot: "Research", pricing: "Freemium", overview: "Elicit is an AI research assistant that finds, summarizes, and organizes academic papers to speed up literature reviews.", key_features: ["Paper search", "Auto summaries", "Data extraction", "Citation export"], use_cases: ["Academic research", "Literature review", "Evidence synthesis"], pros: ["Saves research time", "High quality summaries"], cons: ["Academic focused only", "Limited free searches"] },
  { name: "Consensus", slug: "consensus", url: "https://consensus.app", subcategory_id: 35, subcategory_snapshot: "Research", pricing: "Freemium", overview: "Consensus is an AI search engine for scientific research that extracts findings directly from peer-reviewed papers.", key_features: ["Scientific search", "Consensus meter", "Study snapshots", "Claim detection"], use_cases: ["Health research", "Evidence-based decisions", "Academic work"], pros: ["Peer-reviewed sources", "Consensus indicator"], cons: ["Limited to published papers", "Pro needed for full access"] },
  { name: "Lingo.ai", slug: "lingo-ai", url: "https://lingo.ai", subcategory_id: 14, subcategory_snapshot: "Productivity", pricing: "Freemium", overview: "Lingo.ai is an AI workspace that combines notes, tasks, and documents with AI assistance for team productivity.", key_features: ["AI notes", "Task management", "Team collaboration", "Templates"], use_cases: ["Project management", "Meeting notes", "Team wikis"], pros: ["All-in-one workspace", "Clean UI"], cons: ["Early stage product", "Limited integrations"] },
  { name: "Surfer SEO", slug: "surfer-seo", url: "https://surferseo.com", subcategory_id: 21, subcategory_snapshot: "SEO", pricing: "Paid", overview: "Surfer SEO is an AI-driven on-page SEO optimization tool that analyzes top-ranking pages and guides content creation.", key_features: ["Content editor", "SERP analyzer", "Keyword research", "Audit tool"], use_cases: ["SEO content writing", "Site audits", "Keyword strategy"], pros: ["Data-driven approach", "Detailed guidelines"], cons: ["Expensive", "Steep learning curve"] },
  { name: "Fathom", slug: "fathom", url: "https://fathom.video", subcategory_id: 17, subcategory_snapshot: "Meetings", pricing: "Freemium", overview: "Fathom is a free AI meeting recorder and note-taker that summarizes your calls and highlights key moments.", key_features: ["Auto recording", "AI summaries", "CRM sync", "Highlight reels"], use_cases: ["Sales calls", "Team meetings", "Client calls"], pros: ["Generous free plan", "CRM integration"], cons: ["Zoom only", "Privacy concerns"] },
  { name: "Fireflies.ai", slug: "fireflies-ai", url: "https://fireflies.ai", subcategory_id: 17, subcategory_snapshot: "Meetings", pricing: "Freemium", overview: "Fireflies.ai is an AI meeting assistant that records, transcribes, and analyzes conversations across video platforms.", key_features: ["Auto transcription", "Smart search", "Topic tracking", "Analytics"], use_cases: ["Sales calls", "Recruiting", "Team meetings"], pros: ["Works on all platforms", "Searchable transcripts"], cons: ["Storage limits on free", "Accuracy varies"] },
  { name: "Airtable AI", slug: "airtable-ai", url: "https://airtable.com/ai", subcategory_id: 31, subcategory_snapshot: "Data", pricing: "Freemium", overview: "Airtable AI adds powerful AI capabilities to your databases, enabling data categorization, summarization, and generation.", key_features: ["AI field generation", "Data categorization", "Summarization", "Scripting"], use_cases: ["Database management", "Content operations", "Project tracking"], pros: ["Flexible database", "Easy AI integration"], cons: ["Credits system", "Complex for beginners"] },
  { name: "Codeium", slug: "codeium", url: "https://codeium.com", subcategory_id: 28, subcategory_snapshot: "Code", pricing: "Free", overview: "Codeium is a free AI code completion tool supporting 70+ languages with IDE plugins and chat capabilities.", key_features: ["70+ languages", "IDE plugins", "Chat mode", "Codebase context"], use_cases: ["Code completion", "Code explanation", "Refactoring"], pros: ["Completely free", "Fast completions"], cons: ["Less capable than Copilot", "Newer product"] },
  { name: "Tabnine", slug: "tabnine", url: "https://tabnine.com", subcategory_id: 28, subcategory_snapshot: "Code", pricing: "Freemium", overview: "Tabnine is an AI code assistant that provides whole-line and full-function code completions trained on open-source code.", key_features: ["Local AI option", "Team learning", "Privacy mode", "IDE support"], use_cases: ["Code completion", "Enterprise development", "Privacy-sensitive coding"], pros: ["Privacy focused", "Local model option"], cons: ["Less creative than GPT", "Slower updates"] },
  { name: "Looka", slug: "looka", url: "https://looka.com", subcategory_id: 8, subcategory_snapshot: "Design", pricing: "Paid", overview: "Looka is an AI-powered logo maker and brand design platform that creates professional brand identities in minutes.", key_features: ["Logo generation", "Brand kit", "Business card design", "Social templates"], use_cases: ["Startup branding", "Small business logos", "Brand identity"], pros: ["Professional results", "Complete brand kit"], cons: ["Pay per download", "Limited post-purchase edits"] },
  { name: "Remove.bg", slug: "remove-bg", url: "https://remove.bg", subcategory_id: 6, subcategory_snapshot: "Image", pricing: "Freemium", overview: "Remove.bg uses AI to instantly remove backgrounds from images with a single click, supporting bulk processing.", key_features: ["Instant removal", "HD downloads", "API access", "Bulk processing"], use_cases: ["E-commerce photos", "Profile pictures", "Design assets"], pros: ["Extremely fast", "Accurate results"], cons: ["Limited free downloads", "Struggles with complex backgrounds"] },
  { name: "Cleanup.pictures", slug: "cleanup-pictures", url: "https://cleanup.pictures", subcategory_id: 6, subcategory_snapshot: "Image", pricing: "Freemium", overview: "Cleanup.pictures is an AI-powered tool that removes unwanted objects, people, and text from photos instantly.", key_features: ["Object removal", "HD output", "Batch processing", "API"], use_cases: ["Photo editing", "Real estate photos", "Product images"], pros: ["Simple and fast", "Good accuracy"], cons: ["Limited free uses", "Complex scenes are harder"] },
  { name: "Khroma", slug: "khroma", url: "https://khroma.co", subcategory_id: 8, subcategory_snapshot: "Design", pricing: "Free", overview: "Khroma is an AI color tool that learns your color preferences and generates infinite palettes, gradients, and typography combos.", key_features: ["Personalized palettes", "Typography pairing", "Gradient generator", "Color search"], use_cases: ["UI design", "Branding", "Art direction"], pros: ["Highly personalized", "Completely free"], cons: ["Learning phase required", "No export to design tools"] },
  { name: "Scribe", slug: "scribe", url: "https://scribehow.com", subcategory_id: 14, subcategory_snapshot: "Productivity", pricing: "Freemium", overview: "Scribe automatically creates step-by-step guides with screenshots by recording your workflow as you complete tasks.", key_features: ["Auto documentation", "Screenshot capture", "Instant sharing", "Browser extension"], use_cases: ["Process documentation", "Training guides", "SOPs"], pros: ["Zero manual effort", "Instant guides"], cons: ["Limited styling", "Browser extension required"] },
  { name: "Motion", slug: "motion", url: "https://usemotion.com", subcategory_id: 18, subcategory_snapshot: "Scheduling", pricing: "Paid", overview: "Motion uses AI to automatically schedule your tasks and meetings into the optimal time slots in your calendar.", key_features: ["Auto scheduling", "Task prioritization", "Calendar sync", "Team scheduling"], use_cases: ["Time management", "Team planning", "Deep work scheduling"], pros: ["Truly automated scheduling", "Reduces decision fatigue"], cons: ["Expensive", "Takes time to trust AI"], },
  { name: "Reclaim.ai", slug: "reclaim-ai", url: "https://reclaim.ai", subcategory_id: 18, subcategory_snapshot: "Scheduling", pricing: "Freemium", overview: "Reclaim.ai intelligently schedules tasks, habits, and meeting buffers into your Google Calendar using AI.", key_features: ["Habit scheduling", "Smart meetings", "Task sync", "Buffer time"], use_cases: ["Work-life balance", "Focus time", "Team availability"], pros: ["Great habit tracking", "Google Calendar native"], cons: ["Google Calendar only", "Limited team features on free"] },
  { name: "Bardeen", slug: "bardeen", url: "https://bardeen.ai", subcategory_id: 15, subcategory_snapshot: "Automation", pricing: "Freemium", overview: "Bardeen is a no-code automation tool that connects your web apps and automates repetitive tasks with AI agents.", key_features: ["Browser automation", "AI agent", "Scraping", "1000+ integrations"], use_cases: ["Lead generation", "Data scraping", "Workflow automation"], pros: ["Works in browser", "Powerful scraping"], cons: ["Browser only", "Complex for beginners"] },
  { name: "Phind", slug: "phind", url: "https://phind.com", subcategory_id: 28, subcategory_snapshot: "Code", pricing: "Freemium", overview: "Phind is an AI search engine for developers that provides instant answers to programming questions with code examples.", key_features: ["Code-focused search", "Real-time web", "VS Code extension", "GPT-4 powered"], use_cases: ["Debugging", "Learning new tech", "Code examples"], pros: ["Developer focused", "Real-time results"], cons: ["Limited to coding topics", "Pro for advanced models"] },
  { name: "Krisp", slug: "krisp", url: "https://krisp.ai", subcategory_id: 9, subcategory_snapshot: "Audio", pricing: "Freemium", overview: "Krisp is an AI noise cancellation app that removes background noise and echo from calls in real time.", key_features: ["Noise cancellation", "Echo removal", "Meeting assistant", "Works on any app"], use_cases: ["Remote work", "Podcasting", "Customer support"], pros: ["Works on all apps", "No hardware needed"], cons: ["Limited free minutes", "CPU intensive"] },
  { name: "Speechify", slug: "speechify", url: "https://speechify.com", subcategory_id: 33, subcategory_snapshot: "Education", pricing: "Freemium", overview: "Speechify converts any text, PDF, or webpage into natural-sounding audio so you can listen to anything at speed.", key_features: ["Text to speech", "Speed reading", "Chrome extension", "OCR scan"], use_cases: ["Studying", "Accessibility", "Multitasking reading"], pros: ["Natural voices", "Works on any content"], cons: ["Best voices are paid", "Mobile focused"] },
  { name: "Consensus AI", slug: "consensus-ai-search", url: "https://consensus.app", subcategory_id: 35, subcategory_snapshot: "Research", pricing: "Freemium", overview: "An AI-powered academic search engine that finds answers to health and science questions from peer-reviewed research.", key_features: ["Evidence synthesis", "Claim detection", "GPT-4 summaries", "Citation export"], use_cases: ["Medical research", "Science questions", "Evidence review"], pros: ["Peer-reviewed only", "Trustworthy sources"], cons: ["Science topics only", "Limited free queries"] },
  { name: "Typeface", slug: "typeface", url: "https://typeface.ai", subcategory_id: 20, subcategory_snapshot: "Marketing", pricing: "Paid", overview: "Typeface is an enterprise AI content platform that generates on-brand content personalized to your brand's voice and style.", key_features: ["Brand training", "Content generation", "Team workflows", "Integrations"], use_cases: ["Enterprise marketing", "Brand content", "Multi-channel campaigns"], pros: ["Strong brand consistency", "Enterprise grade"], cons: ["Expensive", "Enterprise focus only"] },
  { name: "Wordtune", slug: "wordtune", url: "https://wordtune.com", subcategory_id: 14, subcategory_snapshot: "Productivity", pricing: "Freemium", overview: "Wordtune is an AI writing companion that suggests better ways to express your ideas with rewrites and smart suggestions.", key_features: ["Sentence rewriting", "Tone adjustment", "Expand/shorten", "Summaries"], use_cases: ["Email writing", "Reports", "Non-native speakers"], pros: ["Intuitive interface", "Great for rewording"], cons: ["Not a full writing tool", "Limited free rewrites"] },
];

// Remove the gods field if it accidentally got in
const cleaned = tools.map(({ gods, ...t }) => t);

const payload = cleaned.map(t => ({
  user_id: USER_ID,
  url: t.url,
  name: t.name,
  slug: t.slug,
  subcategory_id: t.subcategory_id,
  subcategory_snapshot: t.subcategory_snapshot,
  pricing: t.pricing,
  overview: t.overview,
  key_features: t.key_features ?? [],
  use_cases: t.use_cases ?? [],
  pros: t.pros ?? [],
  cons: t.cons ?? [],
  status: "published",
  submitted_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}));

const res = await fetch(`${SUPABASE_URL}/rest/v1/tool_submissions`, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    "apikey": SERVICE_KEY,
    "Authorization": `Bearer ${SERVICE_KEY}`,
    "Prefer": "return=minimal",
  },
  body: JSON.stringify(payload),
});

if (res.ok) {
  console.log(`✅ Inserted ${payload.length} tools successfully`);
} else {
  const err = await res.text();
  console.error("❌ Error:", err);
}
